### PR TITLE
Be clear this is for Docker CE

### PR DESCRIPTION
**Pull request by duglin**
Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by friism** [comment]
lgtm

**Comment by friism** [comment]
@duglin on second thought I think it might be ok for this repo to cover both Docker for Windows issues and general Windows container issues. Is there a particular reason you think the wording you proposed is better?

**Comment by duglin** [comment]
I was under the impression that there was supposed to be a clear line between CE and EE and that the for-* stuff was CE.  The download link on this page ( https://www.docker.com/products/docker#/windows ) takes me to the CE download page.

**Comment by akimd** [comment]
@gtardif The Mac counterpart of this PR was installed.  Either we revert of the Mac, or we apply the Win one, but currently we are inconsistent.

**Comment by gtardif** [comment]
@garethr this is part of the stuff that needs to be reviewed with @JimCodified

**Comment by gtardif** [comment]
@gh2k You can take a look at http://success.docker.com/article/where-to-get-help-with-windows

**Comment by gtardif** [comment]
Merging this since it makes things a bit more clear, even if there might be subsequent changes.

**Pull request merged**
